# Generated by Django 6.0.2 on 2026-02-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_project_options_remove_project_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('industry', models.CharField(choices=[('3d_design', '3D Design'), ('ecommerce', 'E-commerce'), ('accounting', 'Accounting'), ('marketing', 'Marketing'), ('saas', 'SaaS'), ('other', 'Other')], max_length=50)),
                ('project_description', models.TextField()),
                ('hosting_info', models.TextField(blank=True)),
                ('deadline_communication', models.TextField(blank=True)),
                ('required_features', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
